### ISSUE TITLE
Help with one of my projects

### ISSUE THREAD

**Issue by akshitadixit** [Aashishkumar123/Python-Tkinter-Series#7]
Hey @Aashishkumar123, it was great to see your expertise with tkinter. 

Please check out my [Project](https://github.com/DSC-IIIT-Kalyani/ENCODN) on tkinter. I'm actually stuck at a point where I need to sort of create notebook tabs inside a frame which is nested inside an outer notebook tab. Could you please help me out with it or suggest a simpler approach? Thank you.

**Comment by akshitadixit** [comment]
Hi @Aashishkumar123 thank you for the notif, sorry if the issue bothered you. Over the last one year I've grown so much. I'm glad 
I asked for help back then 😄

**Comment by Aashishkumar123** [comment]
No worries 😊 Sorry @akshitadixit I couldn’t checked your issues 😅
